main: e_driver.o Event.o Sender.o Packet.o Node.o
	g++ -o e_driver e_driver.o Event.o Sender.o Node.o

e_driver.o: e_driver.cpp Event.h Packet.h Sender.h
	g++ -Wall -c e_driver.cpp

Event.o: Event.cpp Event.h Sender.h Packet.h
	g++ -Wall -c Event.cpp

Sender.o: Sender.cpp Sender.h Packet.h Node.h
	g++ -Wall -c Sender.cpp

Packet.o: Packet.cpp Packet.h Node.h
	g++ -Wall -c Packet.cpp

Node.o: Node.cpp Node.h
	g++ -Wall -c Node.cpp

clean:
	rm *.o